server:
  shutdown: immediate

spring:
  application:
    name: kunstner
  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: false
  datasource:
    username: kunstner_api_user
    password: ${DB_USER_PW}
    url: jdbc:postgresql://localhost:5432/kunstner
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      idle-timeout: 15000
      maximum-pool-size: 10
      minimum-idle: 5
  flyway:
    enabled: true
    user: kunstner_api_flyway
    password: ${FLYWAY_USER_PW}
    url: jdbc:postgresql://localhost:5432/kunstner
  security:
    user:
      name: admin
      password: ${ADMIN_USER_PW}

logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 50MB
      clean-history-on-start: true
  level:
    root: INFO


---

spring:
  config:
    activate:
      on-profile: production

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

---

spring:
    config:
        activate:
            on-profile: test
    security:
      user:
        password: admin
    flyway:
      password: password
    datasource:
      password: password
